services:
  my-php-app:
    build: .
    environment:
      XDEBUG_MODE: 'debug'
      XDEBUG_TRIGGER: '${XDEBUG_TRIGGER:-1}'
      XDEBUG_CONFIG: 'client_host=${XDEBUG_CLIENT_HOST:-host.docker.internal} client_port=${XDEBUG_PORT_SERVICES:-9008}'
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=myApp}'
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - web

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - web

  nginx:
    image: nginx
    depends_on:
      - my-php-app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public/
      - ./storage/app/public:/var/www/html/storage/app/public
    ports:
      - "80:80"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  database:
  public:

